### PR TITLE
Refactor codebase to TS

### PR DESCRIPTION
**Pull request by SpBills**
This is the tracking PR for refactoring the codebase to TS. Currently it compiles, but needs a bit more work and use to prove itself mergeable.

### CODE REVIEW

**Comment by SpBills** [comment]
The docker compose now works and is running on the server.

Need to write tests for this...

**Comment by SpBills** [comment]
This is really scary and I don't want to merge it, so I would prefer someone more skilled than me to review and confirm that this is equivalent to the old JS code.

**Review by JacksonIsenhower — CHANGES_REQUESTED** [review]
Made a suggestion on code that may have been missed in the TS refactor. There also seems to be a typo that has existed in the code. While it only affects a single file here, there's a chance that something in another application tries to reference the misspelled version. Otherwise the code looks good.

**Review by JacksonIsenhower — APPROVED** [review]
LGTM

**Pull request merged**
